### ISSUE TITLE
Auto shutdown does not work if warn while printing is enabled

### ISSUE THREAD

**Issue by dnasir** [jneilliii/OctoPrint-Tasmota#111]
I have OctoPrint set up so that it would wait for the hotend temp to reach 80C before calling M81. However, I have recently discovered that enabling the warn while printing option causes the printer not to turn off.

I'm not sure if this is a bug or a feature, and I haven't seen any documentation on this, so I thought I'd post an issue to verify.

I'm running version 0.8.14 of the plugin, due to the latest version not working with OctoPod. And I have Tasmota 9.2.0 installed on my Sonoff Basic.

**Comment by jneilliii** [comment]
> I have OctoPrint set up so that it would wait for the hotend temp to reach 80C before calling M81.

How are you doing this, that's not part of this plugin? If you want that type of power off I highly recommend the idle timer option instead of using the gcode triggers. However, if you use the gcode triggers you just need to increase the amount of time on the gcode delay setting in order to give your printer plenty of time to clear it's buffer prior to attempting the power off. This way the printer is not in a printer state when the power off command gets sent.

**Comment by dnasir** [comment]
Under OctoPrint Settings > Printer > GCODE scripts, I have the following code `After print job completes`

```
M109 R80 ;wait for hotend to cool to 80
M81 ender3.lan 1 ;turn off printer
M81 ender3-lights.lan 1 ;turn off lights
```

Which waits for the hotend to cool down to 80C before executing the subsequent lines.

I can live with the prompt whenever I want to turn the printer off, but I'll look into adding some sort of delay before attempting to turn the printer off. Thanks for the suggestion.
