### ISSUE TITLE
mDNS support please

### ISSUE THREAD

**Issue by MkLHX** [jneilliii/OctoPrint-Tasmota#133]
Hello thx for this great plugin, but can you add mDNS compatibility please?
In 3D printers farm it look more simple to link printer with it's tasmota device by using mDNS instead of ip address.
mDNS allow us to don't care about ip fixing or DHCP lease.

**Comment by jneilliii** [comment]
standard hostnames should work in lieu of ip address. have you tried that yet?

**Comment by MkLHX** [comment]
Hi @jneilliii,
thx for your answer. I tried the hostname but no success.
![image](https://user-images.githubusercontent.com/17542841/110141314-50152080-7dd5-11eb-9093-dc2fdcbad533.png)

![image](https://user-images.githubusercontent.com/17542841/110141486-7b980b00-7dd5-11eb-8055-b4be709fa1d1.png)

**Comment by jneilliii** [comment]
What about from your router's interface for connected devices? Is that how the hostname is showing as well?

**Comment by jneilliii** [comment]
@foosel don't you use hostname in your tasmota plugin setup? Was there anything you had to do special for the hostname to resolve properly?

**Comment by MkLHX** [comment]
The device in my router:
![image](https://user-images.githubusercontent.com/17542841/110142328-55269f80-7dd6-11eb-9f32-35abf62ad425.png)

![image](https://user-images.githubusercontent.com/17542841/110142361-5eb00780-7dd6-11eb-8d30-f74342294312.png)
note: the mDNS i now deprecated on tasmota 9.3.1 but this is a ghost of mDNS from old firmware 8.2.

The device is reachable
![image](https://user-images.githubusercontent.com/17542841/110142471-7dae9980-7dd6-11eb-8746-c0ceb06f740d.png)

**Comment by foosel** [comment]
@jneilliii I don't use mdns anymore tbh (it's more trouble than not, at least on my lan) but let my unifi setup take care of DNS.

**Comment by jneilliii** [comment]
Based on what I'm seeing on the Tasmota side the reason they disable it by default is because of it's additional load on the esp devices. Taking into account they may completely remove that in a future release (based on your deprecation comment), and Gina's comment above about troubles with the implementation in general, I'm not willing to put the work in to implement this feature request. If that actually is not deprecated by Tasmota firmware I would consider implementing but would need concise details on how to get it configured in my network and functional first, since I'm completely unfamiliar with the mDNS protocol/process.

**Comment by foosel** [comment]
If tasmota offers this you could still support device *discovery* via zeroconf. That is way less of a nightmare than mdns and actually works quite well.

Take a look at the bundled discovery plugin's helpers.

**Comment by MkLHX** [comment]
Thx all for returns.
I'm going too look about zeroconf.
