### ISSUE TITLE
Cancel power off delay

### ISSUE THREAD

**Issue by AndiP1234** [jneilliii/OctoPrint-Tasmota#148]
Hi jneiliii,

is´t possible to cancel the power off delay with a new print or a power on command?
v 1.0.3 with OctoPrint 1.6.0

I set up the power off delay for M81 at 7 min. The M81 command is in the end code.

1. example:
regualar print is finished and I start a new print, the power off delay is still runing and after the first layers the printer goes off.

2. example:
I use the plugin "Continuous Print". At the bed clearing code (code before starting the next print) I call the M80 command, but this command doesn´t cancel the power off delay.

**Comment by jneilliii** [comment]
Ah, so just so I understand completely. The idle timeout expires and triggers the abort timer. The next file starts but the abort timer doesn't get reset, and therefore still powers off once the abort timeout is reached. I guess what's happening here is that continuous print isn't initializing a new print, because this would have been accounted for [here](https://github.com/jneilliii/OctoPrint-Tasmota/blob/e325c895c40469166519f971ce9a0ccc78952e79/octoprint_tasmota/__init__.py#L383-L391) on the print start event. Also on the M80 command, that should also reset the idle timer [here](https://github.com/jneilliii/OctoPrint-Tasmota/blob/e325c895c40469166519f971ce9a0ccc78952e79/octoprint_tasmota/__init__.py#L468) during the turn on command. Are you including the IP address of the tasmota device in the command? In either case, I can adapt the code to fix it, just need more details as to how your settings are configured. Can you please share screenshots?

**Comment by AndiP1234** [comment]
Yes, you unterstand it.

The M8x commands are with the IP address and channel number.
M80 192.168.0.130 1
M81 192.168.0.130 1

[plugin_tasmota_debug.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/6399600/plugin_tasmota_debug.log)

![settings 1](https://user-images.githubusercontent.com/38299266/116571260-32fb5a80-a90b-11eb-84f3-db05735ecee2.PNG)
![settings 2](https://user-images.githubusercontent.com/38299266/116571261-3393f100-a90b-11eb-96d8-a068a3ec3cc3.PNG)

**Comment by jneilliii** [comment]
```
[2021-04-29 14:56:49,206] DEBUG: Idle timeout reached after 30 minute(s). Turning heaters off prior to powering off plugs.
[2021-04-29 14:56:49,207] DEBUG: Heaters below temperature.
[2021-04-29 14:56:49,208] DEBUG: Checking timelapse status before shutting off power...
[2021-04-29 14:56:49,208] DEBUG: Starting abort power off timer.
[2021-04-29 14:57:19,272] DEBUG: Automatically powering off enabled plugs.
```

I'm just curious if 30 seconds just isn't long enough of an abort timeout?

**Comment by AndiP1234** [comment]
The issue happens at
```
[2021-04-29 14:34:44,780] DEBUG: Sending gcode off
or
[2021-04-29 14:26:46,902] DEBUG: Received M80 command, attempting power on of 192.168.0.130 index 1.
```
I added some comments to the log file.
[plugin_tasmota_debug (1).log](https://github.com/jneilliii/OctoPrint-Tasmota/files/6400141/plugin_tasmota_debug.1.log)


At 14:56 the printer was allready off.  At the most time I ignore the timeout because octoprint isn´t open at a browser, but it´s okay :)

**Comment by jneilliii** [comment]
I think I may have this issue resolved with the above commit. If you could test the 1.1.0rc1 release and verify that would be great. You can change the plugin's release channel in OctoPrint's Software Update settings to `Release Candidate` and upgrade when prompted. If you are already on that release channel, you should get an update notice once your local cache times out, or if you force a check.
