### ISSUE TITLE
Issues when printing from printer SD card

### ISSUE THREAD

**Issue by Philpagan** [jneilliii/OctoPrint-Tasmota#165]
Hi, due to serial connection troubles, I often need to print Gcode files from the printer SD card. However, in that case, the Tasmota plugin does not work. Different cases
- when turning both printer and octoprint on and with no further action : idle timeout is taken into account and the power is switched off after the mentioned time.
- when printing local files, both idle timeout or M81 commands are taken into account and the power is switched off.
- when printing files from the printer SD card, either started from Octoprint or the printer panel
    - idle timeout is ignored and the printer remains On at the end of the print
    - M81 commands (even entered into the Octoprint Gcode Scripts) show up in the terminal but are not taken into account and the printer remains On. Nota : when the same command is manually entered in the terminal, the power switches Off
Log files and snapshots attached
![Octoprint_GcodeScript](https://user-images.githubusercontent.com/44428700/135149275-4c833bdc-1b4a-4b03-879f-f211ae17ac72.png)
![Tasmotaplugin_M81_pic1](https://user-images.githubusercontent.com/44428700/135149301-27b2e9d5-d6b0-460f-a689-0a40f2064604.png)
![Tasmotaplugin_M81_pic2](https://user-images.githubusercontent.com/44428700/135149310-c0d78982-80cf-4b14-9486-9267f4f1f114.png)
[plugin_tasmota_debug_IdleTimeOutCase.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/7246667/plugin_tasmota_debug_IdleTimeOutCase.log)
[plugin_tasmota_debug_M81Case.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/7246669/plugin_tasmota_debug_M81Case.log)

.

**Comment by jneilliii** [comment]
I think the issue here might be timing. When the Tasmota receives the signal to power off in any method, it always checks to see if the printer is in "operational" state or not. Because that command is going through the queue after your set and wait temp, that time is probably exceeding the gcode off delay configured in the plugin's settings. Increasing that delay for the gcode off would probably resolve the issue in that case. 

That still does not explain why the idle timeout may not be getting triggered properly. I will attempt to do replicate your situation this weekend if possible and get back to you.

**Comment by Philpagan** [comment]
It makes sense @jneilliii as the previous command is to wait for the hotend temp to go down to 50°C which involves that the print is still on going up to this point and I've let the GCODE Off Delay set to 0. I'll set it to 10 or 20 sec and test. I let you know. Thank you.

**Comment by Philpagan** [comment]
Good News @jneilliii , with a Gcode Off Delay set to 10 sec, the M81 command is taken into account and Power turned Off !
You found up the solution for the M81 case.
[plugin_tasmota_debug_M81OffDelay10sec.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/7250095/plugin_tasmota_debug_M81OffDelay10sec.log)
