### ISSUE TITLE
[Question] Power off RPi first then printer

### ISSUE THREAD

**Issue by JMVS** [jneilliii/OctoPrint-Tasmota#179]
My setup:
The RPi is connected to the printer's PSU and the printer PSU is connected to the mains via a Sonoff POW2 with Tasmota. The printer is an Ender 3v2 with [JyersUI firmware](https://github.com/Jyers/Marlin/).
I have two goals:
1) Shutdown RPi safely and then the printer when idle for XX minutes.
2) Shutdown RPi safely and then the printer via GCode M81 (via the printer's LCD screen using Host Actions for Octoprint plugin)

This is how I currently have configured OctoPrint-Tasmota:
POW2:
![imagen](https://user-images.githubusercontent.com/7751148/166328950-90e3e0b7-7963-4bed-85d9-484f4035acd3.png)
Plugin:
![imagen](https://user-images.githubusercontent.com/7751148/166329049-2454efda-8ae7-45f1-91d6-33be64248455.png)

Right now I can do (2) but it seems to almost immediately shutdown the RPi (status LED still blinking when switching relay off). I've tried different settings and (1) might just work now (I have to re-test).
Powering off by the icon in the top bar of Octoprint's UI seems to be working just fine:
![imagen](https://user-images.githubusercontent.com/7751148/166371027-c51c07af-9fe1-4188-97c2-a1a745adc4fa.png)

Anyway, if someone could check my settings and let me know if anything should be changed it would be greatly appreciated.

**Comment by jneilliii** [comment]
When I was testing this before I took a screenshot of my config and added it to the readme. I'm not sure if it's because you put 0 secs in for system command or not, but [this](https://github.com/jneilliii/OctoPrint-Tasmota#examples) is what I had and it worked. I wouldn't think increasing the timer delay would cause an issue. Enable debug logging and restart OctoPrint and we can see how the process is loop is happening when it fails. That should also help verify the gcode command process, etc. I do know that on delay countdown timer has to be larger than 0. I think I've seen that cause issues before for others.

**Comment by JMVS** [comment]
The Delay for "Run System Command Before Off" did the trick! I used 1 and started working as intended. Thanks!
