### ISSUE TITLE
Power off on idle not working on MK4

### ISSUE THREAD

**Issue by Baune8D** [jneilliii/OctoPrint-Tasmota#202]
As title says, the MK4 never power off. I also have a MK3S+ and that works fine.

Anything i can do to help, just say so 🙂

**Comment by jneilliii** [comment]
That's because prusa asked weird stuff to the temperature reporting and the plugin tries to turn off a heater `X` that it can't with standard commands. I've fixed this in my TP-Link Smart plug plugin and can add the same filter when I have some time, more details [here] (https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/issues/336).

**Comment by Baune8D** [comment]
That would be great! Looking forward to it 🙂

**Comment by jneilliii** [comment]
Added in the above commit and available in version 1.1.4rc2. You can change the plugin's release channel in OctoPrint's Software Update settings to `Release Candidate` and upgrade when prompted.

**Comment by Baune8D** [comment]
Thank you, it works great! 😄
