### ISSUE TITLE
'power off after print finishes' checkbox.

### ISSUE THREAD

**Issue by diamaunt** [jneilliii/OctoPrint-Tasmota#204]
It would be really nice if there was a 'power off after print finishes' button on the main screen somewhere.

At present, I can set an idle timeout, but if I'm starting things up and end up tweaking something in the slicer a little to long, I'll turn around and the machine's back off.  not a huge deal, but it'd be really nice if there were a way to say 'power off after print finishes', for those things that I want to leave printing and go to bed, but not have it shut itself off other times.

**Comment by jneilliii** [comment]
That's what the toggle button is for in the sidebar. It allows for toggling the idle timeout quickly from the main page. 

![image](https://github.com/jneilliii/OctoPrint-Tasmota/assets/5249455/82ace7e5-8354-42c5-a16a-b14e6e204703)

Otherwise, instead of using idle timeout, use gcode triggers and add those to your end gcode scripts in your slicer or in OctoPrint's GCODE Scripts settings.

**Comment by diamaunt** [comment]
My apologies, that's down on the bottom of the stack, and I haven't scrolled down that far. 

Thank you.

**Comment by jneilliii** [comment]
no problem. I tend to use either dragon order or UI Customizer plugins to re-organize it to the top on my printers.

**Comment by diamaunt** [comment]
Oh, thank you very much, I was looking for something to let me rearrange the sidebar, and hadn't gotten to anything good in the zillions of plugins :)  plus, been busy today.
