### ISSUE TITLE
Turn automatically on.

### ISSUE THREAD

**Issue by Snackez** [jneilliii/OctoPrint-Tasmota#32]
Is it possible to turn on the Printer when i´m starting a Printing Job ? And afterwards off ?

**Comment by Quintin9801** [comment]
I have my printer set to automatically turn off with a gcode command at the
end of my print (in octoprint ending gcode) however I’m not sure about
automatically turning it on when you hit “print” because your printer has
to be connected before you click “print”. You can use the connect
automatically connect to your octoprint when you turn it on by checking
“auto connect”. If you would like any guidance I’ve been using this plugin
for quite some time and I love the automation it provides!

**Comment by Quintin9801** [comment]
These are my settings for reference, if you are using a sonoff basic you
will also need to check “singe relay” in the main settings page.

**Comment by jneilliii** [comment]
In it's current form the printer has to be powered on and connected in order for the plugin to be able to give the commands to control the plug/relay. I included the use of M80 gcode commands for power on for users that were using plugs/relays for external stuff like lights and fans, etc. You can still use the buttons in the navbar to power on your printer though.
