### ISSUE TITLE
Feature: Cancel shutdown, if printer is currently printing?

### ISSUE THREAD

**Issue by exetico** [jneilliii/OctoPrint-Tasmota#49]
I can't spot this option, and it's a huge problem for me.

I would like to have a feature, which skips the "Power Off" command, if another print is ongoing.

If i fx has generated a GCODE, and forgot that M81is in the end, it's triggered after the print is done. I then, starting the next print, and 10 minutes after, it's turning off :( (I have a delay defined to 10 minutes, so my Pi can render my timelaps before).

So, an option for "Cancel Turn-off, if printer is currently printing"

And maybe even "Extend the Turn-off, if the printer is still processing timelaps" or so? :D 

I've considered to just stop using this plugin, and implement all the things in Node Red, however, i like that the logics are within my OctoPrint-env :-)

**Comment by jneilliii** [comment]
I've done this with my other plugin.  It shouldn't be too hard or take too long to integrate the same changes here. I'll try to add this and #44 over the holidays.

**Comment by exetico** [comment]
That brilliant!

Btw; Are the other plugin, just the MQTT version, or what? Cause that would be fine to use instead.

**Comment by jneilliii** [comment]
Yeah, the Tasmota-MQTT plugin has the fix for canceling shutdown if printing, but not thermal monitoring (more work for me to do now...).  Both are in the TPLink-Smartplug plugin. IMHO the Tasmota-MQTT plugin is more advanced than this one, but the additional infrastructure setup isn't for everyone. I think it's best feature is automatically detecting a change in the plug with the MQTT subscription and not have to enable a polling option.

I just pushed a new branch for testing that has both features integrated in this plugin.  If you could test out for me prior to release that would be great.  Use the URL below in plugin manager to upgrade.  It unfortunately will clear out all the plug settings, so you may want to grab a screenshot of your plug's setting to be able to set back up.

https://github.com/jneilliii/OctoPrint-Tasmota/archive/0.8.8.zip

To avoid the shutdown while printing you have to enable the option on your plug to Warn while printing and the gcode trigger delay needs to be enough time for your printer to clear it's gcode buffer. The 10 minutes you have configured should be plenty.

**Comment by exetico** [comment]
Are the main focus on the MQTT edition, or?

Cause i'm use to MQTT, and has no problem with changing to that, instead.

However, now that you're asking, i'll test 0.8.8.zip :-)

**Comment by jneilliii** [comment]
Not necessarily my main focus, I try to maintain all of them.

**Comment by exetico** [comment]
Sure. I fully understand, that it's not possible to keep every thing up-to-date, so i would just switch to the mainly updated on, if there was any :D I'll install the plugin, and update, after a few tests.

**Comment by exetico** [comment]
I've tested it a few times. It went fine, for both "Auto poweroff", and triggered by GCODE. If another print was ongoing, it didn't turn off the printer. And, while not printing after the first print, it did turn off, as it should :-)
