### ISSUE TITLE
turn off the printer

### ISSUE THREAD

**Issue by tical40** [jneilliii/OctoPrint-Tasmota#57]
Hi, first of all thanks a lot for the great plugin. I tried to control my Tasmota socket to turn off the printer when i shut down octoprint but unfortunately it does not work. probably i am using the wrong command. i would be very grateful for some information. best regards Alex

**Comment by jneilliii** [comment]
What are your settings now, and I'll tell you what you need to change or you can look at previous closed issues with the same question.

**Comment by tical40** [comment]
![Unbenannt](https://user-images.githubusercontent.com/61226577/74855387-e7314680-5340-11ea-8a10-80ba201feb56.JPG)

**Comment by jneilliii** [comment]
Ok, there is no way to tell the printer to turn off when OctoPrint is getting shut-down, but you can instruct OctoPrint to shutdown once the print is complete.  I assume you are trying to shutdown your pi cleanly and then power off the printer.  In order to do that you'll need to make the settings like this.

![image](https://user-images.githubusercontent.com/5249455/74865373-08813b00-531f-11ea-8867-e938b233397b.png)

The interface looks a little different because I'm prepping to release a new version, which you may also need in order for the gcode trigger to work properly, but once the update is released those settings above should allow you to add the `M81 192.168.178.51 1` to your end gcode script either in OctoPrint's GCODE scripts settings for print complete or your slicer's end gcode section.  The new version also adds a new feature for automatic power off on print complete which is triggered by the print complete event and you don't have to fuss with the gcode triggers.

**Comment by tical40** [comment]
Sorry, but I don't want the printer to be switched off when printing is finished because I often print in succession, but only when I'm completely done and shut down octoprint
________________________________

**Comment by jneilliii** [comment]
That's the beauty of the new automatic power off option.  If you start another print it automatically aborts the previous queued power off command and you just keep going.  Setting the abort timeout to a high value will give you plenty of time to queue up the next print, or automatically shutdown/power off everything once the timer runs out. Outside of that, what you want to do is not possible to my knowledge.

**Comment by tical40** [comment]
Thank you very much, I will test it.
________________________________
