### ISSUE TITLE
username and password

### ISSUE THREAD

**Issue by stofakiller** [jneilliii/OctoPrint-Tasmota#6]
Hi,

It doesnt work if i use user and password

I get this from the URL: Need user=<username>&password=<password>

**Comment by jneilliii** [comment]
I'll look into incorporating that in a future release. Can you verify it works for you if you don't have authentication enabled?

**Comment by stofakiller** [comment]
Ok, yes i can use it without, i have to set device to empty

In the future, maybe it can use mqtt, so it also can read the state of the relay?

**Comment by jneilliii** [comment]
For simplicity and not require setting up a MQTT server, etc. I'm going to stick with web commands.  I've integrated authentication mechanisms into the dev branch.  If you don't mind testing it and report back if it works for you that would be great.  Because of the data change, when you install it will clear out your previous devices and you'll have to add them back.  To install use the link below in plugin manager.

https://github.com/jneilliii/OctoPrint-Tasmota/archive/dev.zip

**Comment by Xeroxxx** [comment]
I never checked with Username Password. 

Works like a charm, thanks for creating this plugin :)

**Comment by jneilliii** [comment]
Thanks.  Now that someone else besides me has upgraded, I'll push the updates to master. I am working on a MQTT version of this plugin.  You can follow it's activity over at [OctoPrint-TasmotaMQTT](https://github.com/jneilliii/OctoPrint-TasmotaMQTT).  

Currently the master branch has a functional simple interface that is able to subscribe to a single plug via its topic setting.  Requires the MQTT plugin to be installed and configured to connect to a MQTT broker.

**Comment by jneilliii** [comment]
Incorporated into Release [0.2.0](https://github.com/jneilliii/OctoPrint-Tasmota/releases/tag/0.2.0).
