### ISSUE TITLE
Why SetOption26?

### ISSUE THREAD

**Issue by herrwusel** [jneilliii/OctoPrint-Tasmota#69]
This is just a question. Why does the plugin need the plug to have the 26 option enabled? If it is enabled, home assistant isn't capable of updating the switch's state anymore.

**Comment by jneilliii** [comment]
It depends on how you're connecting HomeAssistant I assume. The difference between SetOption26 being on or off is that the response from the device matches the request being given, so for example if you send the request `Power1 0` to turn the power off the status is returned as `Power1 off`. Otherwise, there was issues where if you send the command `Power1 off` you would get a response `Power off` or something like that. Basically, the response from Tasmota would not match the request and for multiple relay devices that was a problem. 

But to be honest, I just tested and if you leave the index value blank and SetOption26 is off the plugin will still work, at least from the navbar button.

**Comment by herrwusel** [comment]
Thanks! Index was somehow set. As you said removing it, solved my problem.
