### ISSUE TITLE
Provide the same for esphome

### ISSUE THREAD

**Issue by torwag** [jneilliii/OctoPrint-Tasmota#95]
Hi, 
as I switched almost all my devices to esphome (personal taste), I wonder if this plugin could work with esphome as well. A new plugin would be almost identical (the octoprint side would be exactly the same) it would be "just" another api to call.
Thus, I believe it would make sense to be able to select either esphome or tasmota as switch device.
Willing to help and do this, instead of a fork, if someone could give me a start and if @jneilliii agrees that this is a good idea and that a PR like this could make it into the plugin officially.

**Comment by jneilliii** [comment]
I personally think it would be better to have this as it's own fork/plugin implementation otherwise no-one would ever find it when searching for esphome on the repo. There are also probably things in this plugin that might not work for esphome, like backlog commands. I'd be more than happy to help you with the fork and provide guidance.

**Comment by anthonylavado** [comment]
I think I'll be willing to take this on. I'll fork and take a look.

**Comment by jneilliii** [comment]
Nice @anthonylavado if you have any questions don't hesitate to ping me. I'm also regularly on the OctoPrint Discord, there's a #dev-plugins channel there where a bunch of us hang out and help each other.
