### ISSUE TITLE
Start Printer - 60 seconds idle - Printer shuts down

### ISSUE THREAD

**Issue by B0IIE** [jneilliii/OctoPrint-Tasmota#99]
Hi,

first of all, thank you for your work and for providing this pluging.
When I power up my printer via the sonoff leaf it idle for one minute it shuts down again.
Is this supposed to happen?
I have the Off Countdown Delay set to 60 seconds, but am under the impression this means something else.

![grafik](https://user-images.githubusercontent.com/33508932/98451192-c9f90e00-2143-11eb-929d-059570fb9a48.png)

**Comment by jneilliii** [comment]
The idle time is on the main settings interface, that is where you need to adjust your idle timeout. Not within the device's configuration. This countdown delay is used for sending the command to the plug and allowing for clean shutdown, which appears to be what you are using it for.

**Comment by B0IIE** [comment]
Sorry for not providing all information. I have set the idle timeout on the main page to 30 minutes, which works fine when I send a command to octoprint within the first 60 seconds.
I did some further testing and I found out that the shutdown isn´t the Off Delay Countdown but it comes from your plugin (I disabled both and the printer behaved accordingly).
I then changed the GCODE Off Delay from 60 s to 
120 s with no shut down.
62 s with no shut down
60 s (again..) with no shut down

So this playing around somehow solved the problem but I don´t have any idea how..
![grafik](https://user-images.githubusercontent.com/33508932/98459605-b75ef300-219c-11eb-8e36-5fb87d0ae050.png)

**Comment by jneilliii** [comment]
it could have possibly been a stale setting that wasn't getting refreshed server side possibly. During your testing at some point, restarting got things back in sync to your actually settings and are not working as expected?

**Comment by B0IIE** [comment]
Yes, now everything works as expected.

**Comment by jneilliii** [comment]
Do you have more details to share as to the steps/settings I can use to replicate your issue since you have re-opened it?

**Comment by B0IIE** [comment]
The issue still exists. I didn´t use my printer for a while or when I did, I had the plugin dissabled.
I know gave it another try. For that I deleted all the plugin data and started from scratch.
Here you can see my setup:
![grafik](https://user-images.githubusercontent.com/33508932/99898363-3118d580-2ca1-11eb-82c3-e874758cd381.png)
![grafik](https://user-images.githubusercontent.com/33508932/99898371-3f66f180-2ca1-11eb-9c4a-f90caa1f0b87.png)

Just now I was quick enough to get a screenshot of the countdown for stopping the shutdown:
![grafik](https://user-images.githubusercontent.com/33508932/99898326-e1d2a500-2ca0-11eb-94c6-c30f80ac245e.png)

Here is the behaviour I observed.
Printed something last night. - The plugin shut the printer down properly.
Started the printer this morning by switching the Sonoff on with an android app on my phone.
Within a minute the printer got shut down again. I managed to take the above screenshot but couldnt´t abort it as the webinterface was loading.
Restarted the printer with the app.
Printer got shut down after 15 minutes (as configured).
Restarted the printer with the app.
Printer got shut down after 15 minutes (as configured).

I can´t pin down why the printer shuts down sometimes within a minute and sometimes not. But it seems as if its only after the first startup of after a longer downtime.

**Comment by troet** [comment]
I am having the same problem. I have one Tasmota that powers my Ender 5 and the RasPi running OctoPrint. 
The setup is supposed to turn off printer and pie on idle, which it does just fine. But the tasmota turns off a minute or so after powering on again (which i trigger either manually or with the web interface of the tasmota - happens in both cases). 

Is there anything we can do to provide debugging information (log files or something) to better look into that?

![tasmo_2](https://user-images.githubusercontent.com/2272035/100537904-95511180-322c-11eb-9863-0cbe3105541b.jpg)
![tasmo_1](https://user-images.githubusercontent.com/2272035/100537857-3d1a0f80-322c-11eb-9a48-0480cb76c9a8.jpg)

**Comment by jneilliii** [comment]
I think I've made some progress on this, but haven't been able to thoroughly test yet. If you guys want to give it a go you can copy/paste the URL below into plugin manager > get more > ...from URL and click Install.

```
https://github.com/jneilliii/OctoPrint-Tasmota/archive/0.8.16rc3.zip
```

**Comment by B0IIE** [comment]
I installed the new version yesterday evening and tested it this morning. But sadly the behaviour didn´t change. (I didn´t change anything else)

**Comment by troet** [comment]
> https://github.com/jneilliii/OctoPrint-Tasmota/archive/0.8.16rc3.zip

Before I could try the rc the final 0.8.16 was released.

With 0.8.16 the problem persists for me. Can we provide you with more information?

**Comment by jneilliii** [comment]
No, I don't think so. I just have to recreate the exact settings and see what's going on. The changes I made were incorporated from my TPLink plugin and it did resolve the same issue with startup for it. Sorry for the quick release, had to get it out because of OctoPrint 1.5.0 compatibility.

**Comment by nnguyen555** [comment]
Oddly enough, this is happening to me as well. I finally got the plugin to work as it should with a simple fix from jneilliii. However, every time I start up Octoprint, the 60 second countdown window starts and it shuts down my printer.

**Comment by jneilliii** [comment]
I'm going to see if moving the idler start to printer connected rather than startup event helps in this situation. There's some race condition somewhere, I just haven't had much time to trace it yet.

**Comment by Pointer-de** [comment]
Hi.
Don't know if it is the same problem, but here ist my "try and error" - hope my english is not to bad to understand ^^

Blitzwolf-SHP7 V2 with Tasmota 9.1.0, 230V-Dual-relay-plug
Tasmota-Plugin 0.8.16

Port/Index1 = Printer
Port/Index2 = Octoprint (Octopi)

**1st problem:**
I switch on manually over Tasmota-WebGUI "ON" at Port2...
_17:11:56 RSL: RESULT = {"POWER2":"ON"}
17:11:56 RSL: POWER2 = ON_

Octopi starts briefly but then this happens...
_17:13:15 RSL: RESULT = {"Delay":20}
17:13:15 RSL: RESULT = {"POWER1":"OFF"}
17:13:15 RSL: POWER1 = OFF
17:13:15 RSL: RESULT = {"Delay":300}
17:13:45 RSL: RESULT = {"POWER2":"OFF"}
17:13:45 RSL: POWER2 = OFF_

Immediately (<30min) switch on again over Tasmota-WebGUI, it stays on without problems.

BUT if I switch it on again after more than 30 minutes (Next hour, day, week...) it goes off again as shown above. As if it were counting the idle-timer even though it was switched off.
_17:47:07 RSL: RESULT = {"POWER2":"ON"}
17:47:07 RSL: POWER2 = ON
17:48:23 RSL: RESULT = {"Delay":20}
17:48:23 RSL: RESULT = {"POWER1":"OFF"}
17:48:23 RSL: POWER1 = OFF
17:48:24 RSL: RESULT = {"Delay":300}
17:48:54 RSL: RESULT = {"POWER2":"OFF"}
17:48:54 RSL: POWER2 = OFF_

I wonder about the reported delay-times. There are no 20sec and 300sec set in the plugin as seen on the screenshots
![Tasmota-Config-Main](https://user-images.githubusercontent.com/32867677/103028779-b7526100-4558-11eb-93a8-7932b0dc39a2.png)
![Tasmota-Config-Drucker](https://user-images.githubusercontent.com/32867677/103028787-bb7e7e80-4558-11eb-9db1-f83bd0163089.png)
![Tasmota-Config-Octopi](https://user-images.githubusercontent.com/32867677/103028792-bde0d880-4558-11eb-9837-5d26e319d252.png)


2nd Problem:
And in the end ... if I shut down the Octopi myself with the pluginbutton in the top, it switches the relay immediately. No chance to give the Octopi time to shut down although a delay of 25 seconds has been set
_17:58:33 RSL: RESULT = {"POWER2":"OFF"}
17:58:33 RSL: POWER2 = OFF_
![Myself_off](https://user-images.githubusercontent.com/32867677/103028719-9ab62900-4558-11eb-87f1-5f8143327a6b.png)

If the Plugin shutdown the Octopi because of 30mins of idle, a delay time is set (other than set in the plugin, but better than nothing) and the Rasppi could shutdown itself before power off
_19:11:44 RSL: RESULT = {"POWER2":"ON"}
19:11:44 RSL: POWER2 = ON_
(i've done something on the Octoprint till 19:13)

_19:43:20 RSL: RESULT = {"Delay":20}
19:43:20 RSL: RESULT = {"POWER1":"OFF"}
19:43:20 RSL: POWER1 = OFF
19:43:21 RSL: RESULT = {"Delay":300}

19:43:39 RSL: RESULT = {"POWER2":"OFF"}
19:43:39 RSL: POWER2 = OFF_

I hope here ist something usefull. If you need more info, I'll try ;-)

**Comment by jneilliii** [comment]
@Pointer-de I think part of your problem might be related to using countdown timers for both relay setups for the same device (since you have a multiple relay device).  If you disable that option for the relay that doesn't need to shutdown the pi I think it will help. Also, I notice you have debug logging enabled, could you upload your entire plugin_tasmota_debug.log file by dragging it into a comment here?

**Comment by Pointer-de** [comment]
Before (the printer wasn't on for a while) there weren't any problems, but I don't remember the plugin version from that time - sorry


[plugin_tasmota_debug (1).log](https://github.com/jneilliii/OctoPrint-Tasmota/files/5736767/plugin_tasmota_debug.1.log)

**Comment by jneilliii** [comment]
I think your issue might be related to #108 as that one also is shutting down the pi prior to powering off the plug. I still think in your situation having both using the backlog command (countdown timers) the second one is overwriting the first one.

**Comment by jneilliii** [comment]
Could you please update and let me know if the latest 1.0.1 version is still exhibiting this behavior for you or not?

**Comment by nnguyen555** [comment]
It seems to be working as it should with the latest version. Thank you.
